### ISSUE TITLE
MC: 1.19.2

### ISSUE THREAD

**Issue by Hanmingxuan** [KlNon/clearItem#1]
[21:27:54 ERROR]: Thread Craft Scheduler Thread - 64 - ClearItem failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.2.jar:git-Paper-133]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2426) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.getNMSEntities(CraftWorld.java:1079) ~[paper-1.19.2.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.getEntities(CraftRegionAccessor.java:412) ~[paper-1.19.2.jar:git-Paper-133]
        at com.mcsyr.clearitem.tools.clearWorldItem(tools.java:122) ~[clearItem-3.3.0-SNAPSHOT.jar:?]
        at com.mcsyr.clearitem.tools.lambda$clearWorld$2(tools.java:115) ~[clearItem-3.3.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-133]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:27:54 WARN]: [ClearItem] Plugin ClearItem v3.3.0-SNAPSHOT generated an exception while executing task 34778
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.19.2.jar:git-Paper-133]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2426) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.getNMSEntities(CraftWorld.java:1079) ~[paper-1.19.2.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.getEntities(CraftRegionAccessor.java:412) ~[paper-1.19.2.jar:git-Paper-133]
        at com.mcsyr.clearitem.tools.clearWorldItem(tools.java:122) ~[clearItem-3.3.0-SNAPSHOT.jar:?]
        at com.mcsyr.clearitem.tools.lambda$clearWorld$2(tools.java:115) ~[clearItem-3.3.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-133]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:27:54 ERROR]: Thread Craft Scheduler Thread - 80 - ClearItem failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.2.jar:git-Paper-133]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2426) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.getNMSEntities(CraftWorld.java:1079) ~[paper-1.19.2.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.getEntities(CraftRegionAccessor.java:412) ~[paper-1.19.2.jar:git-Paper-133]
        at com.mcsyr.clearitem.tools.clearWorldItem(tools.java:122) ~[clearItem-3.3.0-SNAPSHOT.jar:?]
        at com.mcsyr.clearitem.tools.lambda$clearWorld$2(tools.java:115) ~[clearItem-3.3.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-133]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:27:54 WARN]: [ClearItem] Plugin ClearItem v3.3.0-SNAPSHOT generated an exception while executing task 34779
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.19.2.jar:git-Paper-133]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2426) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.getNMSEntities(CraftWorld.java:1079) ~[paper-1.19.2.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.getEntities(CraftRegionAccessor.java:412) ~[paper-1.19.2.jar:git-Paper-133]
        at com.mcsyr.clearitem.tools.clearWorldItem(tools.java:122) ~[clearItem-3.3.0-SNAPSHOT.jar:?]
        at com.mcsyr.clearitem.tools.lambda$clearWorld$2(tools.java:115) ~[clearItem-3.3.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-133]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:27:55 ERROR]: Thread Craft Scheduler Thread - 82 - ClearItem failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.2.jar:git-Paper-133]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2426) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.getNMSEntities(CraftWorld.java:1079) ~[paper-1.19.2.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.getEntities(CraftRegionAccessor.java:412) ~[paper-1.19.2.jar:git-Paper-133]
        at com.mcsyr.clearitem.tools.clearWorldItem(tools.java:122) ~[clearItem-3.3.0-SNAPSHOT.jar:?]
        at com.mcsyr.clearitem.tools.lambda$clearWorld$2(tools.java:115) ~[clearItem-3.3.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-133]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:27:55 WARN]: [ClearItem] Plugin ClearItem v3.3.0-SNAPSHOT generated an exception while executing task 34780
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.19.2.jar:git-Paper-133]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2426) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.getNMSEntities(CraftWorld.java:1079) ~[paper-1.19.2.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.getEntities(CraftRegionAccessor.java:412) ~[paper-1.19.2.jar:git-Paper-133]
        at com.mcsyr.clearitem.tools.clearWorldItem(tools.java:122) ~[clearItem-3.3.0-SNAPSHOT.jar:?]
        at com.mcsyr.clearitem.tools.lambda$clearWorld$2(tools.java:115) ~[clearItem-3.3.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-133]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

This server is running Paper version git-Paper-133 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 0bf8790)

**Comment by KlNon** [comment]
sorry i have no time to update this plugin before 2022.12.25.    :(

**Comment by Thexiaoyuqaq** [comment]
#4
